KERNEL_BOOT_MULTIBOOT1_ROOT := $(KERNEL_SRC_ROOT)/boot/multiboot1

KERNEL_BOOT_MULTIBOOT1_C_SRCS := \
 $(KERNEL_BOOT_MULTIBOOT1_ROOT)/mb_init.c
KERNEL_BOOT_MULTIBOOT1_ASM_SRCS := \
 $(KERNEL_BOOT_MULTIBOOT1_ROOT)/boot.S

KERNEL_LINKER_SCRIPT := $(KERNEL_BOOT_MULTIBOOT1_ROOT)/linker.ld
