KERNEL_MODULE_ROOT := $(KERNEL_SRC_ROOT)
KERNEL_C_SRCS += \
 $(KERNEL_MODULE_ROOT)/main.c $(KERNEL_MODULE_ROOT)/libc.c $(KERNEL_MODULE_ROOT)/sync.c \
 $(KERNEL_MODULE_ROOT)/memory.c $(KERNEL_MODULE_ROOT)/thread.c \
 $(KERNEL_MODULE_ROOT)/program.c $(KERNEL_MODULE_ROOT)/syscall.c \
 $(KERNEL_MODULE_ROOT)/ipc.c $(KERNEL_MODULE_ROOT)/caps.c \
 $(KERNEL_MODULE_ROOT)/startup/common.c $(PROFILE_SOURCE)
KERNEL_ASM_SRCS += $(KERNEL_MODULE_ROOT)/boot.S
KERNEL_LINKER_SCRIPT := $(KERNEL_MODULE_ROOT)/linker.ld
