KERNEL_MODULE_ROOT := $(KERNEL_SRC_ROOT)
LIBSHARKIX_ROOT := $(SHARKIX_PROJECT_ROOT)/src/libsharkix
LIBSHARKIX_BUILD_ROOT := $(CONFIG_BUILD_ROOT)/libsharkix
LIBSHARKIX_KERNEL_ARTIFACT := $(LIBSHARKIX_BUILD_ROOT)/libsharkix-kernel.a

KERNEL_LINK_LIBS += $(LIBSHARKIX_KERNEL_ARTIFACT)

$(LIBSHARKIX_KERNEL_ARTIFACT): FORCE
	$(MAKE) -C $(LIBSHARKIX_ROOT) \
		BUILD_OUT=$(LIBSHARKIX_BUILD_ROOT) \
		INCLUDE=$(INCLUDE_ROOT) \
		DEBUG=$(DEBUG) \
		$(LIBSHARKIX_KERNEL_ARTIFACT)

KERNEL_C_SRCS += \
 $(KERNEL_MODULE_ROOT)/main.c $(KERNEL_MODULE_ROOT)/console.c $(KERNEL_MODULE_ROOT)/console-serial.c $(KERNEL_MODULE_ROOT)/console-vga.c $(KERNEL_MODULE_ROOT)/libc.c $(KERNEL_MODULE_ROOT)/sync.c \
 $(KERNEL_MODULE_ROOT)/memory.c $(KERNEL_MODULE_ROOT)/thread.c \
 $(KERNEL_MODULE_ROOT)/program.c $(KERNEL_MODULE_ROOT)/syscall.c \
 $(KERNEL_MODULE_ROOT)/ipc.c $(KERNEL_MODULE_ROOT)/caps.c $(KERNEL_MODULE_ROOT)/pmem.c \
 $(KERNEL_MODULE_ROOT)/vmo.c \
 $(KERNEL_MODULE_ROOT)/kvalloc.c \
 $(KERNEL_MODULE_ROOT)/startup/common.c $(PROFILE_SOURCE)
KERNEL_ASM_SRCS += $(KERNEL_MODULE_ROOT)/boot.S
KERNEL_LINKER_SCRIPT := $(KERNEL_MODULE_ROOT)/linker.ld
