KERNEL_MODULE_ROOT := $(KERNEL_SRC_ROOT)
LIBSHARKIX_ROOT := $(SHARKIX_PROJECT_ROOT)/src/libsharkix
LIBSHARKIX_BUILD_ROOT := $(CONFIG_BUILD_ROOT)/libsharkix
LIBSHARKIX_KERNEL_ARTIFACT := $(LIBSHARKIX_BUILD_ROOT)/libsharkix-kernel.a

KERNEL_LINK_LIBS += $(LIBSHARKIX_KERNEL_ARTIFACT)

$(LIBSHARKIX_KERNEL_ARTIFACT): FORCE
	$(MAKE) -C $(LIBSHARKIX_ROOT) \
		BUILD_OUT=$(LIBSHARKIX_BUILD_ROOT) \
		INCLUDE=$(INCLUDE_ROOT) \
		DEBUG=$(DEBUG) \
		$(LIBSHARKIX_KERNEL_ARTIFACT)

KERNEL_C_SRCS += \
 $(KERNEL_MODULE_ROOT)/profiles/common.c $(PROFILE_SOURCE)

$(call include-module,$(KERNEL_MODULE_ROOT)/core)
KERNEL_C_SRCS += $(KERNEL_CORE_C_SRCS)

$(call include-module,$(KERNEL_MODULE_ROOT)/subsystems)
KERNEL_C_SRCS += $(SUBSYSTEM_C_SRCS)

$(call include-module,$(KERNEL_MODULE_ROOT)/boot/multiboot1)
KERNEL_C_SRCS += $(KERNEL_BOOT_MULTIBOOT1_C_SRCS)
KERNEL_ASM_SRCS += $(KERNEL_BOOT_MULTIBOOT1_ASM_SRCS)
