SHARKIX_PROJECT_ROOT := $(abspath $(dir $(SHARKIX_TOPLEVEL_MAKEFILE)))

KERNEL_SRC_ROOT ?= $(SHARKIX_PROJECT_ROOT)/src/kernel
USER_SRC_ROOT ?= $(SHARKIX_PROJECT_ROOT)/src/user
INCLUDE_ROOT ?= $(SHARKIX_PROJECT_ROOT)/include
KERNEL_INCLUDE_ROOT ?= $(INCLUDE_ROOT)/sharkix/kernel
USER_INCLUDE_ROOT ?= $(INCLUDE_ROOT)
MK_ROOT ?= $(SHARKIX_PROJECT_ROOT)/mk
CONFIG_ROOT ?= $(SHARKIX_PROJECT_ROOT)/configs
BUILD_ROOT ?= $(SHARKIX_PROJECT_ROOT)/build
EXTERNAL_ROOT ?= $(SHARKIX_PROJECT_ROOT)/external

CONFIG ?= default
PROFILE ?= normal
DEBUG ?= 0

CC ?= gcc
LD ?= ld
AR ?= ar
OBJCOPY ?= objcopy
MKDIR_P ?= mkdir -p

BUILD_VARIANT = $(if $(filter 1,$(DEBUG)),debug,release)
CONFIG_BUILD_ROOT = $(BUILD_ROOT)/$(CONFIG)/$(PROFILE)/$(BUILD_VARIANT)
KERNEL_OBJ_ROOT = $(CONFIG_BUILD_ROOT)/kernel
USER_OBJ_ROOT = $(CONFIG_BUILD_ROOT)/user
KERNEL_ELF = $(CONFIG_BUILD_ROOT)/kernel.elf

# Module accumulators. Modules append; only documented scalar selections are
# assigned by the selector that owns them.
KERNEL_C_SRCS :=
KERNEL_ASM_SRCS :=
KERNEL_CPPFLAGS :=
KERNEL_CFLAGS = -std=gnu11 -ffreestanding $(if $(filter 1,$(DEBUG)),-O0 -g,-O3) -Wall -Wextra
KERNEL_ASFLAGS := -x assembler-with-cpp -ffreestanding
KERNEL_LDFLAGS = -m $(KERNEL_LINKER_FORMAT) -T $(KERNEL_LINKER_SCRIPT) -nostdlib
USER_ASM_SRCS :=
USER_ASFLAGS :=
USER_LDFLAGS = -m $(USER_LINKER_FORMAT) -T $(USER_LINKER_SCRIPT) -nostdlib
USER_EMBED_SPECS :=
KERNEL_LINKER_SCRIPT :=
KERNEL_LINKER_FORMAT :=

KERNEL_OBJECTS :=
USER_OBJECTS :=
KERNEL_DEPFILES :=
KERNEL_ARCH_MODULE_ROOTS :=
BOOT_ARTIFACTS :=
CLEAN_COMMAND := :
PROFILE_SOURCE :=
