KERNEL_SUBSYSTEMS_ROOT := $(KERNEL_SRC_ROOT)/subsystems

SUBSYSTEM_C_SRCS := \
 $(KERNEL_SUBSYSTEMS_ROOT)/kas.c $(KERNEL_SUBSYSTEMS_ROOT)/kcaps.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/kipc.c $(KERNEL_SUBSYSTEMS_ROOT)/irq.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/notification.c $(KERNEL_SUBSYSTEMS_ROOT)/pmem.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/portio.c $(KERNEL_SUBSYSTEMS_ROOT)/vmo.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/kthread.c
