KERNEL_SUBSYSTEMS_ROOT := $(KERNEL_SRC_ROOT)/subsystems

SUBSYSTEM_C_SRCS := \
 $(KERNEL_SUBSYSTEMS_ROOT)/kas.c $(KERNEL_SUBSYSTEMS_ROOT)/kcaps.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/kipc.c $(KERNEL_SUBSYSTEMS_ROOT)/kirq.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/knotify.c $(KERNEL_SUBSYSTEMS_ROOT)/kpmem.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/kportio.c $(KERNEL_SUBSYSTEMS_ROOT)/kvmo.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/kthread.c
