KERNEL_SUBSYSTEMS_ROOT := $(KERNEL_SRC_ROOT)/subsystems

SUBSYSTEM_C_SRCS := \
 $(KERNEL_SUBSYSTEMS_ROOT)/as.c $(KERNEL_SUBSYSTEMS_ROOT)/caps.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/ipc.c $(KERNEL_SUBSYSTEMS_ROOT)/irq.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/notification.c $(KERNEL_SUBSYSTEMS_ROOT)/pmem.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/portio.c $(KERNEL_SUBSYSTEMS_ROOT)/vmo.c \
 $(KERNEL_SUBSYSTEMS_ROOT)/kthread.c
