PROFILE_SOURCE := $(KERNEL_SRC_ROOT)/startup/testbin_capnames.c

TESTBIN_CAPNAMES_DIR := $(USER_SRC_ROOT)/testbin_capnames
TESTBIN_CAPNAMES_ENTRY_SOURCE := $(TESTBIN_CAPNAMES_DIR)/entry.S
TESTBIN_CAPNAMES_SOURCE := $(TESTBIN_CAPNAMES_DIR)/main.c
TESTBIN_CAPNAMES_LINKER_SCRIPT := $(TESTBIN_CAPNAMES_DIR)/testbin_capnames.ld
TESTBIN_CAPNAMES_ENTRY_OBJECT := $(USER_OBJ_ROOT)/testbin_capnames/entry.o
TESTBIN_CAPNAMES_OBJECT := $(USER_OBJ_ROOT)/testbin_capnames/main.o
TESTBIN_CAPNAMES_ELF := $(USER_OBJ_ROOT)/testbin_capnames/testbin_capnames.elf
TESTBIN_CAPNAMES_BINARY := $(USER_OBJ_ROOT)/testbin_capnames/testbin_capnames.bin
TESTBIN_CAPNAMES_EMBED_OBJECT := $(KERNEL_OBJ_ROOT)/user_testbin_capnames.o
TESTBIN_CAPNAMES_LIBSHARKIX := $(CONFIG_BUILD_ROOT)/libsharkix/libsharkix-user.a

TESTBIN_CAPNAMES_CFLAGS := \
    -std=gnu11 -ffreestanding -O2 -Wall -Wextra \
    -m64 -fno-stack-protector -fno-pic -fno-pie \
    -mno-red-zone -mno-sse -mno-mmx -mno-80387 \
    -fno-asynchronous-unwind-tables
TESTBIN_CAPNAMES_ASFLAGS := -x assembler-with-cpp -ffreestanding -m64
TESTBIN_CAPNAMES_CPPFLAGS := -I$(INCLUDE_ROOT)

USER_LINKER_SCRIPT := $(TESTBIN_CAPNAMES_LINKER_SCRIPT)

TESTBIN_CAPNAMES_BINARY_NAME := $(patsubst $(SHARKIX_PROJECT_ROOT)/%,%,$(TESTBIN_CAPNAMES_BINARY))
TESTBIN_CAPNAMES_BINARY_SYMBOL := _binary_$(subst /,_,$(subst .,_,$(subst -,_,$(TESTBIN_CAPNAMES_BINARY_NAME))))

$(TESTBIN_CAPNAMES_LIBSHARKIX): FORCE
	$(MAKE) -C $(SHARKIX_PROJECT_ROOT)/src/libsharkix \
		BUILD_OUT=$(CONFIG_BUILD_ROOT)/libsharkix \
		INCLUDE=$(INCLUDE_ROOT) \
		DEBUG=$(DEBUG) \
		$(TESTBIN_CAPNAMES_LIBSHARKIX)

$(TESTBIN_CAPNAMES_ENTRY_OBJECT): $(TESTBIN_CAPNAMES_ENTRY_SOURCE)
	$(MKDIR_P) $(@D)
	$(CC) $(TESTBIN_CAPNAMES_CPPFLAGS) $(TESTBIN_CAPNAMES_ASFLAGS) -c $< -o $@

$(TESTBIN_CAPNAMES_OBJECT): $(TESTBIN_CAPNAMES_SOURCE)
	$(MKDIR_P) $(@D)
	$(CC) $(TESTBIN_CAPNAMES_CPPFLAGS) $(TESTBIN_CAPNAMES_CFLAGS) -c $< -o $@

$(TESTBIN_CAPNAMES_ELF): $(TESTBIN_CAPNAMES_ENTRY_OBJECT) $(TESTBIN_CAPNAMES_OBJECT) $(TESTBIN_CAPNAMES_LINKER_SCRIPT) $(TESTBIN_CAPNAMES_LIBSHARKIX)
	$(MKDIR_P) $(@D)
	$(LD) -m $(USER_LINKER_FORMAT) -nostdlib -o $@ \
		$(TESTBIN_CAPNAMES_ENTRY_OBJECT) $(TESTBIN_CAPNAMES_OBJECT) $(TESTBIN_CAPNAMES_LIBSHARKIX) \
		-T $(TESTBIN_CAPNAMES_LINKER_SCRIPT)

$(TESTBIN_CAPNAMES_BINARY): $(TESTBIN_CAPNAMES_ELF)
	$(OBJCOPY) -O binary $< $@

$(TESTBIN_CAPNAMES_EMBED_OBJECT): $(TESTBIN_CAPNAMES_BINARY)
	$(MKDIR_P) $(@D)
	cd $(SHARKIX_PROJECT_ROOT) && $(OBJCOPY) -I binary -O elf64-x86-64 -B i386:x86-64 \
		--rename-section .data=.rodata,alloc,load,readonly,data,contents \
		--redefine-sym $(TESTBIN_CAPNAMES_BINARY_SYMBOL)_start=testbin_capnames_image_start \
		--redefine-sym $(TESTBIN_CAPNAMES_BINARY_SYMBOL)_end=testbin_capnames_image_end \
		$(patsubst $(SHARKIX_PROJECT_ROOT)/%,%,$<) \
		$(patsubst $(SHARKIX_PROJECT_ROOT)/%,%,$@)

USER_OBJECTS += $(TESTBIN_CAPNAMES_EMBED_OBJECT)
