FREERTOS_KERNEL_ROOT := $(KERNEL_SRC_ROOT)/freertos
KERNEL_C_SRCS += \
 $(FREERTOS_KERNEL_ROOT)/tasks.c $(FREERTOS_KERNEL_ROOT)/queue.c \
 $(FREERTOS_KERNEL_ROOT)/list.c $(FREERTOS_KERNEL_ROOT)/event_groups.c \
 $(FREERTOS_KERNEL_ROOT)/stream_buffer.c $(FREERTOS_KERNEL_ROOT)/croutine.c \
 $(FREERTOS_KERNEL_ROOT)/heap_4.c
